In [23]:
import os
os.environ['USE_PYGEOS'] = '0'

import sys
from pathlib import Path
import geopandas as gpd

parent_dir = Path().resolve().parent
sys.path.insert(0, str(parent_dir))
from map2grid import *

In [24]:
gens_gdf = gpd.read_file('../data/osm/vietnam-latest_plants_and_generators.gpkg')
gens_gdf.head()

,osm_id,power,voltage,utility,name,frequency,plant_output_electricity,plant_source,plant_method,generator_output_electricity,generator_source,generator_type,substation,location,cables,circuits,line,layer,osm_id_right,geometry
0,2495831951,generator,NaN,NaN,Nhà máy nhiệt điện HẢi Phòng,NaN,NaN,NaN,NaN,yes,coal,francis_turbine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (106.65356 20.84855)
1,4037744488,plant,NaN,NaN,Nhà máy thủy điện Ialy,NaN,720 MW,hydro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (107.79546 14.22273)
2,4195284426,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500 kW,wind,horizontal_axis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (108.68039 11.20209)
3,4195284427,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500 kW,wind,horizontal_axis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (108.67951 11.20397)
4,4195284428,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500 kW,wind,horizontal_axis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (108.68835 11.20445)

In [25]:
# 步骤 1：新增 installed_capacity 列
def convert_to_mw(value):
    if pd.isnull(value):
        return None
    if "MW" in value:
        return float(value.split()[0])
    elif "kW" in value:
        return float(value.split()[0]) / 1000
    elif "GW" in value:
        return float(value.split()[0]) * 1000
    else:
        raise ValueError(f"Unexpected value: {value}")

In [26]:
installed_capacity = []
for i, row in gens_gdf.iterrows():
    try:
        if pd.notnull(row["plant_output_electricity"]):
            installed_capacity.append(convert_to_mw(row["plant_output_electricity"]))
        elif pd.notnull(row["generator_output_electricity"]):
            installed_capacity.append(convert_to_mw(row["generator_output_electricity"]))
        else:
            installed_capacity.append(None)
    except ValueError as e:
        print("osm_id ", row['osm_id'], ": ", e)
        installed_capacity.append(None)

gens_gdf["installed_capacity"] = installed_capacity

osm_id  2495831951 :  Unexpected value: yes
osm_id  9445033851 :  Unexpected value: yes
osm_id  9445033852 :  Unexpected value: yes
osm_id  9445033853 :  Unexpected value: yes
osm_id  9445033854 :  Unexpected value: yes
osm_id  9742040890 :  Unexpected value: yes
osm_id  9742066679 :  Unexpected value: yes
osm_id  9742066689 :  Unexpected value: yes
osm_id  9742066690 :  Unexpected value: yes
osm_id  9742100904 :  Unexpected value: yes
osm_id  9742100905 :  Unexpected value: yes
osm_id  9742100906 :  Unexpected value: yes
osm_id  9742100907 :  Unexpected value: yes
osm_id  9742100908 :  Unexpected value: yes
osm_id  9742106428 :  Unexpected value: yes
osm_id  9742121170 :  Unexpected value: yes
osm_id  9742121171 :  Unexpected value: yes
osm_id  9742473105 :  Unexpected value: yes
osm_id  9742498114 :  Unexpected value: yes
osm_id  10208684281 :  Unexpected value: yes
osm_id  10208700917 :  Unexpected value: yes
osm_id  11436663294 :  could not convert string to float: '3.x'
osm_id  11436663295 :  could not convert string to float: '3.x'
osm_id  11436663296 :  could not convert string to float: '3.x'
osm_id  11436663297 :  could not convert string to float: '3.x'
osm_id  11436663298 :  could not convert string to float: '3.x'
osm_id  11436663299 :  could not convert string to float: '3.x'
osm_id  11436663300 :  could not convert string to float: '3.x'
osm_id  11436663301 :  could not convert string to float: '3.x'
osm_id  11436663302 :  could not convert string to float: '3.x'
osm_id  11436663303 :  could not convert string to float: '3.x'
osm_id  11436663304 :  could not convert string to float: '3.x'
osm_id  11436663305 :  could not convert string to float: '3.x'
osm_id  11436663306 :  could not convert string to float: '3.x'
osm_id  11436663307 :  could not convert string to float: '3.x'
osm_id  11436663308 :  could not convert string to float: '3.x'
osm_id  11436677944 :  could not convert string to float: '3.x'
osm_id  11436727204 :  could not convert string to float: '3.x'
osm_id  11436727205 :  could not convert string to float: '3.x'
osm_id  11436727206 :  could not convert string to float: '3.x'
osm_id  11436727207 :  could not convert string to float: '3.x'
osm_id  11436727208 :  could not convert string to float: '3.x'
osm_id  11436727209 :  could not convert string to float: '3.x'
osm_id  11436727210 :  could not convert string to float: '3.x'
osm_id  11436727211 :  could not convert string to float: '3.x'
osm_id  11436727212 :  could not convert string to float: '3.x'
osm_id  11436727213 :  could not convert string to float: '3.x'
osm_id  11436727214 :  could not convert string to float: '3.x'
osm_id  11436727215 :  could not convert string to float: '3.x'
osm_id  11436727216 :  could not convert string to float: '3.x'
osm_id  11436727217 :  could not convert string to float: '3.x'
osm_id  11436727218 :  could not convert string to float: '3.x'
osm_id  12189258178 :  Unexpected value: yes
osm_id  12189258179 :  Unexpected value: yes
osm_id  12189258180 :  Unexpected value: yes
osm_id  12189258181 :  Unexpected value: yes
osm_id  12189258182 :  Unexpected value: yes
osm_id  12189258183 :  Unexpected value: yes
osm_id  12189258184 :  Unexpected value: yes
osm_id  12189258185 :  Unexpected value: yes
osm_id  12189258186 :  Unexpected value: yes
osm_id  12199323757 :  Unexpected value: yes
osm_id  12199323758 :  Unexpected value: yes
osm_id  12199323759 :  Unexpected value: yes
osm_id  12199323760 :  Unexpected value: yes
osm_id  12199323761 :  Unexpected value: yes
osm_id  12199323762 :  Unexpected value: yes
osm_id  12199323763 :  Unexpected value: yes
osm_id  12199323764 :  Unexpected value: yes
osm_id  12199323765 :  Unexpected value: yes
osm_id  12199323766 :  Unexpected value: yes
osm_id  12199323767 :  Unexpected value: yes
osm_id  12199323768 :  Unexpected value: yes
osm_id  12199323774 :  Unexpected value: yes
osm_id  12222780813 :  Unexpected value: yes
osm_id  12222780814 :  Unexpected value: yes
osm_id  12222780815 :  Unexpected value: yes
osm_id  12222780816 :  Unexpected value: yes
osm_id  12222780817 :  Unexpected value: yes
osm_id  12222780818 :  Unexpected value: yes
osm_id  12222780819 :  Unexpected value: yes
osm_id  12222780820 :  Unexpected value: yes
osm_id  12222780821 :  Unexpected value: yes
osm_id  12222780822 :  Unexpected value: yes
osm_id  12222780823 :  Unexpected value: yes
osm_id  12222780824 :  Unexpected value: yes
osm_id  12222780825 :  Unexpected value: yes
osm_id  12222780826 :  Unexpected value: yes
osm_id  12222780827 :  Unexpected value: yes
osm_id  12222780828 :  Unexpected value: yes
osm_id  12222780829 :  Unexpected value: yes
osm_id  12222780830 :  Unexpected value: yes
osm_id  12222780831 :  Unexpected value: yes
osm_id  12222780832 :  Unexpected value: yes
osm_id  12222780858 :  Unexpected value: yes
osm_id  12222780859 :  Unexpected value: yes
osm_id  12222780860 :  Unexpected value: yes
osm_id  12222780861 :  Unexpected value: yes
osm_id  12222780862 :  Unexpected value: yes
osm_id  12222780863 :  Unexpected value: yes
osm_id  12222780864 :  Unexpected value: yes
osm_id  12222780865 :  Unexpected value: yes
osm_id  12222780866 :  Unexpected value: yes
osm_id  12222780867 :  Unexpected value: yes
osm_id  12222780868 :  Unexpected value: yes
osm_id  12222780869 :  Unexpected value: yes
osm_id  12222780870 :  Unexpected value: yes
osm_id  12222780871 :  Unexpected value: yes
osm_id  12222780872 :  Unexpected value: yes
osm_id  12222780873 :  Unexpected value: yes
osm_id  12222780874 :  Unexpected value: yes
osm_id  12222780875 :  Unexpected value: yes
osm_id  12222780876 :  Unexpected value: yes
osm_id  12222780877 :  Unexpected value: yes
osm_id  12222780878 :  Unexpected value: yes
osm_id  12222780879 :  Unexpected value: yes
osm_id  12222780880 :  Unexpected value: yes
osm_id  12222780881 :  Unexpected value: yes
osm_id  12222780882 :  Unexpected value: yes
osm_id  12222780883 :  Unexpected value: yes
osm_id  12222780884 :  Unexpected value: yes
osm_id  12222780885 :  Unexpected value: yes
osm_id  12222780886 :  Unexpected value: yes
osm_id  12222780887 :  Unexpected value: yes
osm_id  12222780888 :  Unexpected value: yes
osm_id  12222780889 :  Unexpected value: yes
osm_id  12222780890 :  Unexpected value: yes
osm_id  12222780891 :  Unexpected value: yes
osm_id  12222780892 :  Unexpected value: yes
osm_id  12222780893 :  Unexpected value: yes
osm_id  12222782078 :  Unexpected value: yes
osm_id  12222782079 :  Unexpected value: yes
osm_id  12222782080 :  Unexpected value: yes
osm_id  12222782081 :  Unexpected value: yes
osm_id  12222782082 :  Unexpected value: yes
osm_id  12222782083 :  Unexpected value: yes
osm_id  12222782084 :  Unexpected value: yes
osm_id  12222782085 :  Unexpected value: yes
osm_id  12222782086 :  Unexpected value: yes
osm_id  12222782087 :  Unexpected value: yes
osm_id  12222782088 :  Unexpected value: yes
osm_id  12222782089 :  Unexpected value: yes
osm_id  12222782090 :  Unexpected value: yes
osm_id  12222782091 :  Unexpected value: yes
osm_id  12222782092 :  Unexpected value: yes
osm_id  12222782093 :  Unexpected value: yes
osm_id  12222782094 :  Unexpected value: yes
osm_id  12222782095 :  Unexpected value: yes
osm_id  12222782096 :  Unexpected value: yes
osm_id  12222782097 :  Unexpected value: yes
osm_id  12222782098 :  Unexpected value: yes
osm_id  12222782099 :  Unexpected value: yes
osm_id  12222782100 :  Unexpected value: yes
osm_id  12222789901 :  Unexpected value: yes
osm_id  12222789902 :  Unexpected value: yes
osm_id  12222789979 :  Unexpected value: yes
osm_id  12222789980 :  Unexpected value: yes
osm_id  12222789981 :  Unexpected value: yes
osm_id  12222789982 :  Unexpected value: yes
osm_id  12222789983 :  Unexpected value: yes
osm_id  12222789984 :  Unexpected value: yes
osm_id  12222789985 :  Unexpected value: yes
osm_id  12222789986 :  Unexpected value: yes
osm_id  12222789987 :  Unexpected value: yes
osm_id  12222789988 :  Unexpected value: yes
osm_id  12222789989 :  Unexpected value: yes
osm_id  12222789990 :  Unexpected value: yes
osm_id  12222789991 :  Unexpected value: yes
osm_id  12222789992 :  Unexpected value: yes
osm_id  12222789993 :  Unexpected value: yes
osm_id  12222789994 :  Unexpected value: yes
osm_id  12222789995 :  Unexpected value: yes
osm_id  12222789996 :  Unexpected value: yes
osm_id  12222789997 :  Unexpected value: yes
osm_id  12222789998 :  Unexpected value: yes
osm_id  12222789999 :  Unexpected value: yes
osm_id  12222790000 :  Unexpected value: yes
osm_id  12222790001 :  Unexpected value: yes
osm_id  12222790002 :  Unexpected value: yes
osm_id  12222790003 :  Unexpected value: yes
osm_id  12222790004 :  Unexpected value: yes
osm_id  12222790005 :  Unexpected value: yes
osm_id  12222790006 :  Unexpected value: yes
osm_id  12222790007 :  Unexpected value: yes
osm_id  12222790008 :  Unexpected value: yes
osm_id  12222790009 :  Unexpected value: yes
osm_id  12222790010 :  Unexpected value: yes
osm_id  12222790011 :  Unexpected value: yes
osm_id  12222790012 :  Unexpected value: yes
osm_id  12222790013 :  Unexpected value: yes
osm_id  12222790014 :  Unexpected value: yes
osm_id  12222790015 :  Unexpected value: yes
osm_id  12222790016 :  Unexpected value: yes
osm_id  12222790017 :  Unexpected value: yes
osm_id  12222790018 :  Unexpected value: yes
osm_id  12222790019 :  Unexpected value: yes
osm_id  12222790020 :  Unexpected value: yes
osm_id  12222790021 :  Unexpected value: yes
osm_id  12222790022 :  Unexpected value: yes
osm_id  12222790023 :  Unexpected value: yes
osm_id  12222790024 :  Unexpected value: yes
osm_id  12222790025 :  Unexpected value: yes
osm_id  12222790026 :  Unexpected value: yes
osm_id  12222790027 :  Unexpected value: yes
osm_id  12222790028 :  Unexpected value: yes
osm_id  12222790029 :  Unexpected value: yes
osm_id  12222790030 :  Unexpected value: yes
osm_id  12222790031 :  Unexpected value: yes
osm_id  12222790032 :  Unexpected value: yes
osm_id  12222790033 :  Unexpected value: yes
osm_id  12222790034 :  Unexpected value: yes
osm_id  12222790035 :  Unexpected value: yes
osm_id  12222790036 :  Unexpected value: yes
osm_id  12222790037 :  Unexpected value: yes
osm_id  12222790038 :  Unexpected value: yes
osm_id  12222790039 :  Unexpected value: yes
osm_id  12222790040 :  Unexpected value: yes
osm_id  12222790041 :  Unexpected value: yes
osm_id  12222790042 :  Unexpected value: yes
osm_id  12222790043 :  Unexpected value: yes
osm_id  12222790044 :  Unexpected value: yes
osm_id  12222790045 :  Unexpected value: yes
osm_id  12222790046 :  Unexpected value: yes
osm_id  12222790047 :  Unexpected value: yes
osm_id  12222790048 :  Unexpected value: yes
osm_id  12222790049 :  Unexpected value: yes
osm_id  12222790050 :  Unexpected value: yes
osm_id  12222790051 :  Unexpected value: yes
osm_id  12222790052 :  Unexpected value: yes
osm_id  12222790053 :  Unexpected value: yes
osm_id  12222790054 :  Unexpected value: yes
osm_id  12222790055 :  Unexpected value: yes
osm_id  12222790056 :  Unexpected value: yes
osm_id  12222790057 :  Unexpected value: yes
osm_id  12222790058 :  Unexpected value: yes
osm_id  12222790059 :  Unexpected value: yes
osm_id  12222790060 :  Unexpected value: yes
osm_id  12222790061 :  Unexpected value: yes
osm_id  12222790062 :  Unexpected value: yes
osm_id  12222790063 :  Unexpected value: yes
osm_id  12222790064 :  Unexpected value: yes
osm_id  12222790065 :  Unexpected value: yes
osm_id  12222790066 :  Unexpected value: yes
osm_id  12222790067 :  Unexpected value: yes
osm_id  12222790068 :  Unexpected value: yes
osm_id  12222790069 :  Unexpected value: yes
osm_id  12222790070 :  Unexpected value: yes
osm_id  12222790071 :  Unexpected value: yes
osm_id  12222790072 :  Unexpected value: yes
osm_id  12222790073 :  Unexpected value: yes
osm_id  12222790074 :  Unexpected value: yes
osm_id  12222790075 :  Unexpected value: yes
osm_id  12222790076 :  Unexpected value: yes
osm_id  12222790077 :  Unexpected value: yes
osm_id  12222790078 :  Unexpected value: yes
osm_id  12222790079 :  Unexpected value: yes
osm_id  12222790080 :  Unexpected value: yes
osm_id  12222790081 :  Unexpected value: yes
osm_id  12222790082 :  Unexpected value: yes
osm_id  12222790083 :  Unexpected value: yes
osm_id  12222790084 :  Unexpected value: yes
osm_id  12222790085 :  Unexpected value: yes
osm_id  12222790086 :  Unexpected value: yes
osm_id  12222790087 :  Unexpected value: yes
osm_id  12222790088 :  Unexpected value: yes
osm_id  12222790089 :  Unexpected value: yes
osm_id  12222790090 :  Unexpected value: yes
osm_id  12222790091 :  Unexpected value: yes
osm_id  12222790092 :  Unexpected value: yes
osm_id  12222790093 :  Unexpected value: yes
osm_id  12222790094 :  Unexpected value: yes
osm_id  12222790095 :  Unexpected value: yes
osm_id  12222790096 :  Unexpected value: yes
osm_id  12222790097 :  Unexpected value: yes
osm_id  12222790098 :  Unexpected value: yes
osm_id  12222790099 :  Unexpected value: yes
osm_id  12222790100 :  Unexpected value: yes
osm_id  12222790101 :  Unexpected value: yes
osm_id  12222790102 :  Unexpected value: yes
osm_id  12222790103 :  Unexpected value: yes
osm_id  12222790104 :  Unexpected value: yes
osm_id  12222790105 :  Unexpected value: yes
osm_id  12222790106 :  Unexpected value: yes
osm_id  12222790107 :  Unexpected value: yes
osm_id  12222790108 :  Unexpected value: yes
osm_id  12222790109 :  Unexpected value: yes
osm_id  12222790110 :  Unexpected value: yes
osm_id  12222790111 :  Unexpected value: yes
osm_id  12222790112 :  Unexpected value: yes
osm_id  12222790113 :  Unexpected value: yes
osm_id  12222790114 :  Unexpected value: yes
osm_id  12222790115 :  Unexpected value: yes
osm_id  12222790116 :  Unexpected value: yes
osm_id  12222790117 :  Unexpected value: yes
osm_id  12222790118 :  Unexpected value: yes
osm_id  12222790119 :  Unexpected value: yes
osm_id  12222790120 :  Unexpected value: yes
osm_id  12222790121 :  Unexpected value: yes
osm_id  12222790122 :  Unexpected value: yes
osm_id  12222790123 :  Unexpected value: yes
osm_id  12222790124 :  Unexpected value: yes
osm_id  12222790125 :  Unexpected value: yes
osm_id  12222790126 :  Unexpected value: yes
osm_id  12222790127 :  Unexpected value: yes
osm_id  12222790128 :  Unexpected value: yes
osm_id  12222790129 :  Unexpected value: yes
osm_id  12222790130 :  Unexpected value: yes
osm_id  12222790131 :  Unexpected value: yes
osm_id  12222790132 :  Unexpected value: yes
osm_id  12222790133 :  Unexpected value: yes
osm_id  12222790134 :  Unexpected value: yes
osm_id  12222790164 :  Unexpected value: yes
osm_id  12222790165 :  Unexpected value: yes
osm_id  12222790166 :  Unexpected value: yes
osm_id  12222790167 :  Unexpected value: yes
osm_id  12222790168 :  Unexpected value: yes
osm_id  12222790169 :  Unexpected value: yes
osm_id  12222790170 :  Unexpected value: yes
osm_id  12222790171 :  Unexpected value: yes
osm_id  12222790172 :  Unexpected value: yes
osm_id  12222790173 :  Unexpected value: yes
osm_id  12222790174 :  Unexpected value: yes
osm_id  12222790175 :  Unexpected value: yes
osm_id  12222790176 :  Unexpected value: yes
osm_id  12222790177 :  Unexpected value: yes
osm_id  12222790178 :  Unexpected value: yes
osm_id  12222790448 :  Unexpected value: yes
osm_id  12222790449 :  Unexpected value: yes
osm_id  12222790450 :  Unexpected value: yes
osm_id  12222790451 :  Unexpected value: yes
osm_id  12222790452 :  Unexpected value: yes
osm_id  12222790453 :  Unexpected value: yes
osm_id  12222790454 :  Unexpected value: yes
osm_id  12222790455 :  Unexpected value: yes
osm_id  12222790456 :  Unexpected value: yes
osm_id  12222790457 :  Unexpected value: yes
osm_id  12222790494 :  Unexpected value: yes
osm_id  12222790495 :  Unexpected value: yes
osm_id  12222790496 :  Unexpected value: yes
osm_id  12222790497 :  Unexpected value: yes
osm_id  12222790498 :  Unexpected value: yes
osm_id  12222790499 :  Unexpected value: yes
osm_id  12222790500 :  Unexpected value: yes
osm_id  12222790501 :  Unexpected value: yes
osm_id  12222790502 :  Unexpected value: yes
osm_id  12222790503 :  Unexpected value: yes
osm_id  12222790504 :  Unexpected value: yes
osm_id  12222790505 :  Unexpected value: yes
osm_id  12222790506 :  Unexpected value: yes
osm_id  12222790507 :  Unexpected value: yes
osm_id  12222790508 :  Unexpected value: yes
osm_id  12222790509 :  Unexpected value: yes
osm_id  12222790510 :  Unexpected value: yes
osm_id  12222790511 :  Unexpected value: yes
osm_id  12222790512 :  Unexpected value: yes
osm_id  12222790513 :  Unexpected value: yes
osm_id  12222790514 :  Unexpected value: yes
osm_id  12222790515 :  Unexpected value: yes
osm_id  12222790516 :  Unexpected value: yes
osm_id  12222790517 :  Unexpected value: yes
osm_id  12222790518 :  Unexpected value: yes
osm_id  12222790519 :  Unexpected value: yes
osm_id  12222790520 :  Unexpected value: yes
osm_id  12222790521 :  Unexpected value: yes
osm_id  12222790522 :  Unexpected value: yes
osm_id  12222790523 :  Unexpected value: yes
osm_id  12222790524 :  Unexpected value: yes
osm_id  12222790525 :  Unexpected value: yes
osm_id  12222790526 :  Unexpected value: yes
osm_id  12222790527 :  Unexpected value: yes
osm_id  12222790528 :  Unexpected value: yes
osm_id  12222790529 :  Unexpected value: yes
osm_id  12222790650 :  Unexpected value: yes
osm_id  12222790651 :  Unexpected value: yes
osm_id  12222790652 :  Unexpected value: yes
osm_id  12222790653 :  Unexpected value: yes
osm_id  12222790654 :  Unexpected value: yes
osm_id  12222790655 :  Unexpected value: yes
osm_id  12222790656 :  Unexpected value: yes
osm_id  12222790657 :  Unexpected value: yes
osm_id  12222790658 :  Unexpected value: yes
osm_id  12222790675 :  Unexpected value: yes
osm_id  12222790676 :  Unexpected value: yes
osm_id  12222790677 :  Unexpected value: yes
osm_id  12222790678 :  Unexpected value: yes
osm_id  12222790679 :  Unexpected value: yes
osm_id  12222790680 :  Unexpected value: yes
osm_id  12222790681 :  Unexpected value: yes
osm_id  12222790687 :  Unexpected value: yes
osm_id  12222790688 :  Unexpected value: yes
osm_id  12222790689 :  Unexpected value: yes
osm_id  12222790690 :  Unexpected value: yes
osm_id  12222790691 :  Unexpected value: yes
osm_id  12222790692 :  Unexpected value: yes
osm_id  12222790693 :  Unexpected value: yes
osm_id  12222790694 :  Unexpected value: yes
osm_id  12222790695 :  Unexpected value: yes
osm_id  12222790696 :  Unexpected value: yes
osm_id  12222790697 :  Unexpected value: yes
osm_id  12222790698 :  Unexpected value: yes
osm_id  12222790699 :  Unexpected value: yes
osm_id  12222790700 :  Unexpected value: yes
osm_id  12222790701 :  Unexpected value: yes
osm_id  12222790702 :  Unexpected value: yes
osm_id  12222790703 :  Unexpected value: yes
osm_id  12222790704 :  Unexpected value: yes
osm_id  12222790705 :  Unexpected value: yes
osm_id  12222790706 :  Unexpected value: yes
osm_id  12222790707 :  Unexpected value: yes
osm_id  12222790708 :  Unexpected value: yes
osm_id  12222790709 :  Unexpected value: yes
osm_id  12222790710 :  Unexpected value: yes
osm_id  12222790711 :  Unexpected value: yes
osm_id  12222790712 :  Unexpected value: yes
osm_id  12222790713 :  Unexpected value: yes
osm_id  12222790714 :  Unexpected value: yes
osm_id  12222790715 :  Unexpected value: yes
osm_id  12222790716 :  Unexpected value: yes
osm_id  12222790717 :  Unexpected value: yes
osm_id  12222790718 :  Unexpected value: yes
osm_id  12222790719 :  Unexpected value: yes
osm_id  12222790720 :  Unexpected value: yes
osm_id  12222790721 :  Unexpected value: yes
osm_id  12222790722 :  Unexpected value: yes
osm_id  12222790723 :  Unexpected value: yes
osm_id  12222790724 :  Unexpected value: yes
osm_id  12222790725 :  Unexpected value: yes
osm_id  12222790726 :  Unexpected value: yes
osm_id  12222790727 :  Unexpected value: yes
osm_id  12222790728 :  Unexpected value: yes
osm_id  12222790729 :  Unexpected value: yes

In [36]:
# 步骤 2：新增 energy_source 列
gens_gdf["energy_source"] = gens_gdf["plant_source"].combine_first(gdf["generator_source"])

# # 保留处理后的 GeoDataFrame
# processed_gdf = gens_gdf.copy()

In [37]:
# 步骤 3：统计 energy_source 的唯一值
unique_energy_sources = gens_gdf["energy_source"].dropna().unique()
print("Unique energy sources:", unique_energy_sources)

Unique energy sources: ['coal' 'hydro' 'wind' 'biofuel' 'diesel' 'biogas' 'solar' 'gas' 'gas;oil'
 'oil' 'waste']

In [38]:
gens_gdf[gens_gdf["energy_source"].isin(["diesel"])]

,osm_id,power,voltage,utility,name,frequency,plant_output_electricity,plant_source,plant_method,generator_output_electricity,...,substation,location,cables,circuits,line,layer,osm_id_right,geometry,installed_capacity,energy_source
23,5246574100,generator,NaN,NaN,Trạm cấp xăng An Bình - CA.TPCT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (105.78503 10.01066),NaN,diesel

In [39]:
# Step 1: 对 filtered_gdf 的 energy_source 进行对应
# 创建一个映射字典，将 energy_source 映射到对应的 INSTALLED CAPACITY (MW)
energy_source_mapping = {
    "hydro": "Hydro",
    "coal": "Coal",
    "oil": "Other Fossil",
    "diesel": "Other Fossil",
    "gas, gas;oil": "Gas",
    "waste": "Bioenergy",
    "biofuel": "Bioenergy", 
    "biogas": "Bioenergy",
    "wind": "Wind",
    "solar": "Solar"
}

# 根据 energy_source 列来映射到 energy_source_stats 列
gens_gdf["energy_source"] = gens_gdf["energy_source"].map(energy_source_mapping)

In [45]:
# 步骤 4：拆分 GeoDataFrame
condition_1 = gens_gdf["installed_capacity"].notnull() & gens_gdf["energy_source"].notnull()
condition_2 = gens_gdf["installed_capacity"].isnull() & gens_gdf["energy_source"].notnull()
condition_3 = gens_gdf["installed_capacity"].notnull() & gens_gdf["energy_source"].isnull()
condition_4 = gens_gdf["installed_capacity"].isnull() & gens_gdf["energy_source"].isnull()

gdf_1 = gens_gdf[condition_1]
gdf_2 = gens_gdf[condition_2]
gdf_3 = gens_gdf[condition_3]
gdf_4 = gens_gdf[condition_4]

print(f"GeoDataFrame 1 (not null installed_capacity and energy_source): {len(gdf_1)} rows")
print(f"GeoDataFrame 2 (null installed_capacity, not null energy_source): {len(gdf_2)} rows")
print(f"GeoDataFrame 3 (not null installed_capacity, null energy_source): {len(gdf_3)} rows")
print(f"GeoDataFrame 4 (null installed_capacity and energy_source): {len(gdf_4)} rows")

GeoDataFrame 1 (not null installed_capacity and energy_source): 539 rows
GeoDataFrame 2 (null installed_capacity, not null energy_source): 1349 rows
GeoDataFrame 3 (not null installed_capacity, null energy_source): 7 rows
GeoDataFrame 4 (null installed_capacity and energy_source): 13 rows

In [46]:
indices_to_remove = pd.concat([gdf_3, gdf_4]).index
filtered_gdf = gens_gdf.drop(indices_to_remove)

In [47]:
print(len(gens_gdf))
print(len(filtered_gdf))

1908
1888

In [48]:
df = pd.read_csv('../data/yearly_full_release_long_format.csv')
installed_capacity_df = df[
    (df["Area"] == "Viet Nam") &
    (df["Year"] == 2023) &
    (df["Category"] == "Capacity") &
    (df["Subcategory"] == "Fuel")
]

installed_capacity_df['Value_MW'] = installed_capacity_df['Value'] * 1000
installed_capacity_df

/tmp/ipykernel_4030750/4214324864.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  installed_capacity_df['Value_MW'] = installed_capacity_df['Value'] * 1000

,Area,Country code,Year,Area type,Continent,Ember region,EU,OECD,G20,G7,ASEAN,Category,Subcategory,Variable,Unit,Value,YoY absolute change,YoY % change,Value_MW
335098,Viet Nam,VNM,2023,Country,Asia,Asia,0.0,0.0,0.0,0.0,1.0,Capacity,Fuel,Bioenergy,GW,0.38,0.00,0.00,380.0
335099,Viet Nam,VNM,2023,Country,Asia,Asia,0.0,0.0,0.0,0.0,1.0,Capacity,Fuel,Coal,GW,27.24,2.63,10.69,27240.0
335100,Viet Nam,VNM,2023,Country,Asia,Asia,0.0,0.0,0.0,0.0,1.0,Capacity,Fuel,Gas,GW,8.15,0.00,0.00,8150.0
335101,Viet Nam,VNM,2023,Country,Asia,Asia,0.0,0.0,0.0,0.0,1.0,Capacity,Fuel,Hydro,GW,22.64,0.11,0.49,22640.0
335102,Viet Nam,VNM,2023,Country,Asia,Asia,0.0,0.0,0.0,0.0,1.0,Capacity,Fuel,Nuclear,GW,NaN,NaN,NaN,NaN
335103,Viet Nam,VNM,2023,Country,Asia,Asia,0.0,0.0,0.0,0.0,1.0,Capacity,Fuel,Other Fossil,GW,NaN,NaN,NaN,NaN
335104,Viet Nam,VNM,2023,Country,Asia,Asia,0.0,0.0,0.0,0.0,1.0,Capacity,Fuel,Solar,GW,17.08,0.38,2.28,17080.0
335105,Viet Nam,VNM,2023,Country,Asia,Asia,0.0,0.0,0.0,0.0,1.0,Capacity,Fuel,Wind,GW,5.89,0.82,16.17,5890.0

In [49]:
gdf_1 = filtered_gdf[condition_1]
gdf_2 = filtered_gdf[condition_2]

/scistor/ivm/mye500/miniconda3/envs/py310/lib/python3.10/site-packages/geopandas/geodataframe.py:1415: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = super().__getitem__(key)
/scistor/ivm/mye500/miniconda3/envs/py310/lib/python3.10/site-packages/geopandas/geodataframe.py:1415: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  result = super().__getitem__(key)

In [51]:
# Step 2: 根据 energy_source_stats 分类计算 gdf_1 中的总值
gdf_1_grouped = gdf_1.groupby("energy_source")["installed_capacity"].sum()

In [52]:
gdf_1_grouped

energy_source
Coal     25711.200
Hydro    21108.758
Solar     5432.222
Wind       975.293
Name: installed_capacity, dtype: float64

In [53]:
# Step 3: 从 Excel 的 installed_capacity 减去 gdf_1 的分类总值
remaining_capacity = {}
for _, row in installed_capacity_df.iterrows():
    category = row["Variable"]
    if category in gdf_1_grouped:
        remaining_capacity[category] = row['Value_MW'] - gdf_1_grouped[category]
    else:
        remaining_capacity[category] = row['Value_MW']

In [54]:
remaining_capacity

{'Bioenergy': 380.0,
 'Coal': 1528.7999999999993,
 'Gas': 8150.0,
 'Hydro': 1531.2419999999984,
 'Nuclear': nan,
 'Other Fossil': nan,
 'Solar': 11647.778,
 'Wind': 4914.707}

In [55]:
# 计算 gdf_2 中每个 energy_source 的 installed_capacity 总和

# 定义一个函数，将剩余容量按比例分配到 gdf_2
def allocate_remaining_capacity(row, remaining_capacity, gdf_2_counts):
    stats = row["energy_source"]
    if stats in remaining_capacity and stats in gdf_2_counts:
        return remaining_capacity[stats] / gdf_2_counts[stats]
    return 0  # 如果没有对应的剩余值或分组总和，分配为 0

# 计算 gdf_2 中每类 energy_source 的行数
gdf_2_counts = gdf_2["energy_source"].value_counts()

# 创建一个新列，将剩余容量分配到 gdf_2 的每一行
gdf_2["installed_capacity"] = gdf_2.apply(
    allocate_remaining_capacity, axis=1, 
    remaining_capacity=remaining_capacity, 
    gdf_2_counts=gdf_2_counts
)

gdf_2

/scistor/ivm/mye500/miniconda3/envs/py310/lib/python3.10/site-packages/geopandas/geodataframe.py:1443: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

,osm_id,power,voltage,utility,name,frequency,plant_output_electricity,plant_source,plant_method,generator_output_electricity,...,substation,location,cables,circuits,line,layer,osm_id_right,geometry,installed_capacity,energy_source
0,2495831951,generator,NaN,NaN,Nhà máy nhiệt điện HẢi Phòng,NaN,NaN,NaN,NaN,yes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (106.65356 20.84855),764.400000,Coal
22,5207569281,generator,NaN,NaN,Trạm biến áp 110/220v,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (105.76793 10.02529),126.666667,Bioenergy
23,5246574100,generator,NaN,NaN,Trạm cấp xăng An Bình - CA.TPCT,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (105.78503 10.01066),NaN,Other Fossil
24,5246576900,generator,NaN,NaN,Tram xang dau QL1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (105.74960 9.99618),126.666667,Bioenergy
25,5573888849,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (108.92361 10.54565),5.256371,Wind
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1903,1308761089,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.67483 13.30744, 107.67484 13.3...",41.013303,Solar
1904,1308761090,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.67319 13.30557, 107.67174 13.3...",41.013303,Solar
1905,1308761091,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.67158 13.30556, 107.67011 13.3...",41.013303,Solar
1906,1308761092,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.66668 13.30942, 107.66509 13.3...",41.013303,Solar
1907,1308761093,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.66549 13.30741, 107.66669 13.3...",41.013303,Solar

In [56]:
gens_gdf_update = pd.concat([gdf_1, gdf_2], ignore_index=True)

In [57]:
gens_gdf_update

,osm_id,power,voltage,utility,name,frequency,plant_output_electricity,plant_source,plant_method,generator_output_electricity,...,substation,location,cables,circuits,line,layer,osm_id_right,geometry,installed_capacity,energy_source
0,4037744488,plant,NaN,NaN,Nhà máy thủy điện Ialy,NaN,720 MW,hydro,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (107.79546 14.22273),720.000000,Hydro
1,4195284426,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500 kW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (108.68039 11.20209),1.500000,Wind
2,4195284427,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500 kW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (108.67951 11.20397),1.500000,Wind
3,4195284428,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500 kW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (108.68835 11.20445),1.500000,Wind
4,4195284429,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500 kW,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (108.67859 11.20585),1.500000,Wind
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1883,1308761089,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.67483 13.30744, 107.67484 13.3...",41.013303,Solar
1884,1308761090,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.67319 13.30557, 107.67174 13.3...",41.013303,Solar
1885,1308761091,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.67158 13.30556, 107.67011 13.3...",41.013303,Solar
1886,1308761092,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.66668 13.30942, 107.66509 13.3...",41.013303,Solar
1887,1308761093,generator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"LINESTRING (107.66549 13.30741, 107.66669 13.3...",41.013303,Solar

In [58]:
gens_gdf_update.to_file("../data/osm/vietnam-latest_plants_and_generators_update_capacity.gpkg", driver="GPKG")