In [ ]:
import pandas as pd
import powerplantmatching as pm

Cartopy not existent.

In [ ]:
cfg = pm.core.get_config(filename=".powerplantmatching_config_update.yaml")

In [13]:
opsd = pm.data.OPSD(config=cfg)
opsd.head()

Empty DataFrame
Columns: [Name, Fueltype, Technology, Set, Country, Capacity, Efficiency, DateIn, DateRetrofit, DateOut, lat, lon, Duration, Volume_Mm3, DamHeight_m, StorageCapacity_MWh, EIC, projectID]
Index: []

In [6]:
geo = pm.data.GEO(config=cfg)
geo.head()

GEO,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
0,Pha Lai Coal Vietnam,Oil,NaN,PP,Vietnam,277.900649,NaN,2001.0,NaN,NaN,21.1165,106.3068,NaN,NaN,NaN,NaN,NaN,GEO-41178
1,Pha Lai Coal Vietnam,Oil,NaN,PP,Vietnam,277.900649,NaN,2001.0,NaN,NaN,21.1165,106.3068,NaN,NaN,NaN,NaN,NaN,GEO-41178
2,Pha Lai Coal Vietnam,Hard Coal,NaN,PP,Vietnam,101.413065,NaN,1983.0,NaN,NaN,21.1155,106.3090,NaN,NaN,NaN,NaN,NaN,GEO-41201
3,Pha Lai Coal Vietnam,Hard Coal,NaN,PP,Vietnam,101.413065,NaN,1983.0,NaN,NaN,21.1155,106.3090,NaN,NaN,NaN,NaN,NaN,GEO-41201
4,Pha Lai Coal Vietnam,Hard Coal,NaN,PP,Vietnam,101.413065,NaN,1983.0,NaN,NaN,21.1155,106.3090,NaN,NaN,NaN,NaN,NaN,GEO-41201

In [14]:
gpd = pm.data.GPD(config=cfg)
gpd.head()

GPD,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
0,Amata,Oil,NaN,PP,Vietnam,13.0,NaN,NaN,NaN,NaN,10.9471,106.9000,NaN,NaN,NaN,NaN,NaN,WRI1030748
1,An Khanh,Hard Coal,NaN,PP,Vietnam,120.0,NaN,2015.0,NaN,NaN,21.5969,105.7670,NaN,NaN,NaN,NaN,NaN,WRI1030773
2,An Khe Kanak,Hydro,NaN,PP,Vietnam,173.0,NaN,2009.0,NaN,NaN,14.0148,108.6796,NaN,NaN,NaN,NaN,NaN,WRI1030828
3,Ayun Ha,Hydro,NaN,PP,Vietnam,3.0,NaN,NaN,NaN,NaN,13.5809,108.2592,NaN,NaN,NaN,NaN,NaN,WRI1030822
4,Ba Ria,Natural Gas,CCGT,PP,Vietnam,389.0,NaN,NaN,NaN,NaN,10.4891,107.1700,NaN,NaN,NaN,NaN,NaN,WRI1030736

In [15]:
gbpt = pm.data.GBPT(config=cfg)
gbpt.head()

AttributeError: 'DataFrame' object has no attribute 'Name'

In [3]:
gcpt = pm.data.GCPT(config=cfg)
gcpt.head()

GCPT,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
0,An Khanh,Hard Coal,Steam Turbine,PP,Vietnam,50.0,NaN,2015.0,NaN,NaN,21.596912,105.766609,NaN,NaN,NaN,NaN,NaN,G100000100190
1,An Khanh,Hard Coal,Steam Turbine,PP,Vietnam,50.0,NaN,2015.0,NaN,NaN,21.596912,105.766609,NaN,NaN,NaN,NaN,NaN,G100000100191
2,Cam Pha,Hard Coal,Steam Turbine,PP,Vietnam,340.0,NaN,2011.0,NaN,NaN,21.006288,107.358044,NaN,NaN,NaN,NaN,NaN,G100000101165
3,Cam Pha,Hard Coal,Steam Turbine,PP,Vietnam,340.0,NaN,2011.0,NaN,NaN,21.006288,107.358044,NaN,NaN,NaN,NaN,NaN,G100000101164
4,Cao Ngan,Hard Coal,Steam Turbine,PP,Vietnam,57.5,NaN,2006.0,NaN,NaN,21.612998,105.815102,NaN,NaN,NaN,NaN,NaN,G100000101199

In [16]:
ggpt = pm.data.GGPT(config=cfg)
ggpt.head()

AttributeError: 'DataFrame' object has no attribute 'Country'

In [17]:
ggtpt = pm.data.GGTPT(config=cfg)
ggtpt.head()

KeyError: ['Capacity']

In [18]:
gnpt = pm.data.GNPT(config=cfg)
gnpt.head()

Empty DataFrame
Columns: [Name, Fueltype, Technology, Set, Country, Capacity, Efficiency, DateIn, DateRetrofit, DateOut, lat, lon, Duration, Volume_Mm3, DamHeight_m, StorageCapacity_MWh, EIC, projectID]
Index: []

In [19]:
gspt = pm.data.GSPT(config=cfg)
gspt.head()

GSPT,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
0,An Cu Solar Farm,Solar,PV,PP,Vietnam,50.0,NaN,NaN,NaN,NaN,10.5095,105.1478,NaN,NaN,NaN,NaN,NaN,G100000811075
1,An Giang Sao Mai Solar Farm,Solar,PV,PP,Vietnam,104.0,NaN,2019.0,NaN,NaN,10.4655,105.0124,NaN,NaN,NaN,NaN,NaN,G100000800922
2,An Giang Sao Mai Solar Farm,Solar,PV,PP,Vietnam,106.0,NaN,2020.0,NaN,NaN,10.5579,104.9915,NaN,NaN,NaN,NaN,NaN,G100000800923
3,Ba Ria Vung Tau Province Solar,Solar,PV,PP,Vietnam,16.3,NaN,2020.0,NaN,NaN,10.5862,107.0435,NaN,NaN,NaN,NaN,NaN,G100001029408
4,Bac Ai District Solar,Solar,PV,PP,Vietnam,5.0,NaN,2020.0,NaN,NaN,11.6611,108.9623,NaN,NaN,NaN,NaN,NaN,G100001029498

In [4]:
gwpt = pm.data.GWPT(config=cfg)
gwpt.head()

GWPT,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
0,Bac Lieu Kosy Offshore Wind Farm,Wind,Offshore,PP,Vietnam,40.5,NaN,2021.0,NaN,NaN,9.1718,105.6710,NaN,NaN,NaN,NaN,NaN,G100000901412
1,Bac Lieu Offshore Wind Farm,Wind,Offshore,PP,Vietnam,16.0,NaN,2013.0,NaN,NaN,9.2367,105.8223,NaN,NaN,NaN,NaN,NaN,G100000901706
2,Bac Lieu Offshore Wind Farm,Wind,Offshore,PP,Vietnam,83.0,NaN,2014.0,NaN,NaN,9.2367,105.8223,NaN,NaN,NaN,NaN,NaN,G100000901708
3,Ben Tre Binh Dai Offshore Wind Farm,Wind,Offshore,PP,Vietnam,49.0,NaN,2021.0,NaN,NaN,10.1507,106.8010,NaN,NaN,NaN,NaN,NaN,G100000900990
4,Ben Tre Binh Dai Offshore Wind Farm,Wind,Offshore,PP,Vietnam,30.0,NaN,2022.0,NaN,NaN,10.0954,106.8110,NaN,NaN,NaN,NaN,NaN,G100000900988

In [20]:
jrc = pm.data.JRC(config=cfg)
jrc.head()

Empty DataFrame
Columns: [Name, Fueltype, Technology, Set, Country, Capacity, Efficiency, DateIn, DateRetrofit, DateOut, lat, lon, Duration, Volume_Mm3, DamHeight_m, StorageCapacity_MWh, EIC, projectID]
Index: []

In [22]:
dfs = [gpd.powerplant.aggregate_units(), geo.powerplant.aggregate_units()]
intersection = pm.matching.combine_multiple_datasets(dfs)

No matches found

In [9]:
gwpt.powerplant.lookup().head(20).to_frame()

                  Capacity
Country Fueltype
Vietnam Wind        7403.1

In [11]:
geo.powerplant.fill_missing_commissioning_years().head()

GEO,Name,Fueltype,Technology,Set,Country,Capacity,Efficiency,DateIn,DateRetrofit,DateOut,lat,lon,Duration,Volume_Mm3,DamHeight_m,StorageCapacity_MWh,EIC,projectID
0,Pha Lai Coal Vietnam,Oil,NaN,PP,Vietnam,277.900649,NaN,2001.0,2001.0,NaN,21.1165,106.3068,NaN,NaN,NaN,NaN,NaN,GEO-41178
1,Pha Lai Coal Vietnam,Oil,NaN,PP,Vietnam,277.900649,NaN,2001.0,2001.0,NaN,21.1165,106.3068,NaN,NaN,NaN,NaN,NaN,GEO-41178
2,Pha Lai Coal Vietnam,Hard Coal,NaN,PP,Vietnam,101.413065,NaN,1983.0,1983.0,NaN,21.1155,106.3090,NaN,NaN,NaN,NaN,NaN,GEO-41201
3,Pha Lai Coal Vietnam,Hard Coal,NaN,PP,Vietnam,101.413065,NaN,1983.0,1983.0,NaN,21.1155,106.3090,NaN,NaN,NaN,NaN,NaN,GEO-41201
4,Pha Lai Coal Vietnam,Hard Coal,NaN,PP,Vietnam,101.413065,NaN,1983.0,1983.0,NaN,21.1155,106.3090,NaN,NaN,NaN,NaN,NaN,GEO-41201